---
name: "Set Up Java Step"
description: "Set up Action"
inputs:
  github-token:
    required: true
runs:
  using: "composite"
  steps:
  - name: "Set Up GraalVM 21"
    uses: "graalvm/setup-graalvm@v1"
    with:
      java-version: 21
      distribution: "graalvm"
      github-token: "${{ inputs.github-token }}"
  - name: "Setup Gradle"
    uses: "gradle/gradle-build-action@v3.0.0-beta.1"
