---
name: "Build, Test & Security Tests"
run-name: "Running commit ${{ github.sha }}"
"on":
- "push"
jobs:
  build-application:
    needs:
    - "setup-workflow"
    runs-on:
    - "ubuntu-latest"
    steps:
    - name: "Set Up Job"
      uses: "fernyettheplant/bdd-testconmtainers-demo/.github/workflows/setup-workflow.yaml@main"
    - name: "Build Application"
      run: "./gradlew clean assemble"
  unit-tests:
    needs:
    - "build-application"
    runs-on:
    - "ubuntu-latest"
    steps:
    - name: "Set Up Job"
      uses: "fernyettheplant/bdd-testconmtainers-demo/.github/workflows/setup-workflow.yaml@main"
    - name: "Build Application"
      run: "./gradlew check"
  integration-test:
    needs:
    - "build-application"
    runs-on:
    - "ubuntu-latest"
    steps:
    - name: "Set Up Job"
      uses: "fernyettheplant/bdd-testconmtainers-demo/.github/workflows/setup-workflow.yaml@main"
    - name: "Setup Testcontainers Cloud Client"
      uses: "atomicjar/testcontainers-cloud-setup-action@v1"
      with:
        token: "${{ secrets.TC_CLOUD_TOKEN }}"
    - name: "Run Integration Tests"
      run: "./gradlew cucumberCli"
