---
name: "Set Up Java Step"
"on":
- "push"
jobs:
  setup-workflow:
    runs-on:
    - "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set Up GraalVM 21"
      uses: "graalvm/setup-graalvm@v1"
      with:
        java-version: 21
        distribution: "graalvm"
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: "Setup Gradle"
      uses: "gradle/gradle-build-action@v3.0.0-beta.1"
