---
name: "Run Integration Tests"
run-name: "${{ github.actor }} is running Integration Tests"
"on":
- "push"
jobs:
  integration:
    runs-on:
    - "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "graalvm/setup-graalvm@v1"
      with:
        java-version: 21
        distribution: "graalvm"
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: "Setup Gradle"
      uses: "gradle/gradle-build-action@2.11.1"
    - name: "Run Gradle"
      run: "./gradlew cucumberCli"
