---
name: "Run Integration Tests"
run-name: "${{ github.actor }} is running Integration Tests"
"on":
- "push"
jobs:
  integration:
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v4.1.1"
    - uses: "actions/setup-java@v3.13.0"
      with:
        java-version: 17
        distribution: "zulu"
        cache: "gradle"
    - name: "Setup Gradle"
      uses: "gradle/gradle-build-action@v2.9.0"
    - name: "Run Gradle"
      run: "./gradlew cucumberCli"
